apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
  namespace: monitoring
data:
  fluent.conf: |
    <source>
      @type tail
      path /var/log/containers/*.log
      pos_file /var/log/fluentd-containers.log.pos
      tag kubernetes.*
      read_from_head true
      <parse>
        @type json
        time_format %Y-%m-%dT%H:%M:%S.%N%Z
      </parse>
    </source>

    <filter kubernetes.**>
      @type kubernetes_metadata
    </filter>

    <match **>
      @type loki
      @id out_loki
      url "http://loki:3100"
      flush_interval 1s
      buffer_chunk_limit 1M
      buffer_max_size 5M
      buffer_path /var/log/fluentd-buffers
      remove_keys kubernetes, stream
      <label>
        job "fluentd"
      </label>
    </match>