apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-webserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow-webserver
  template:
    metadata:
      labels:
        app: airflow-webserver
    spec:
      containers:
        - name: airflow-webserver
          image: apache/airflow:2.9.2
          ports:
            - containerPort: 8080
          volumeMounts:
            - mountPath: "/Users/me/airflow"
              name: airflow-storage
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
      volumes:
        - name: airflow-storage
          persistentVolumeClaim:
            claimName: airflow-pvc