
runnerSet:
  replicas: ${runner_replicas}
  repository: "${github_owner}/${github_repo}"
  image: "ghcr.io/actions-runner-controller/actions-runner:latest"
  env:
    - name: "GITHUB_TOKEN"
      valueFrom:
        secretKeyRef:
          name: "github-actions-secret"
          key: "GITHUB_TOKEN"
  resources:
    requests:
      cpu: "250m"
      memory: "512Mi"
    limits:
      cpu: "500m"
      memory: "1Gi"