apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: airflow
  namespace: monitoring
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: airflow
  namespaceSelector:
    matchNames:
      - default
  endpoints:
    - port: metrics
      interval: 30s